### ISSUE TITLE
beagle API

### ISSUE THREAD

**Issue by seultt** [YoungHeaKim/beagleWPSN#17]
API 설계

로그인
GET /auth/facebook
[
  {
    userName: '',
    photoUrl: '',
    email: '',
  }
]
GET /auth/naver
GET /auth/kakaotalk
GET /auth/google

인덱스 리스트
GET /chat_list
[
  {
    userName: '',
    photoUrl: '',
    like: 3,
    name: '',
    description: '',
    star_at: date,
    // 대화방에 참가한 사람 수의 데이터를 저장하는 column이 없음.
  }
]
GET /chat_list?page=12 //페이지네이션 
GET /chat_list?city=osaka&start_at=171001
[
  {
    // 미정
  }
]

프로필
GET /chat_list/7
[
  {
    userName: '',
    photoUrl: '',
    like: 3,
    name: '',
    description: '',
    message: [
      {
        // 메시지 내용
      },
      {

      },
    ],
    star_at: date,
    // 대화방에 참가한 사람 수의 데이터를 저장하는 column이 없음.
  }
]
DEL /chat_list/7
GET /chat_list?userId=19
[
  {
    photo: '',
    name: '',
    city: '',
    star_at: date,
    // 대화방에 참가한 사람 수의 데이터를 저장하는 column이 없음.
  }
]

**Comment by yujin-min** [comment]
대화방에 참가한 사람의 수를 chat_list라는 대화방과 유저를 연결해 놓은 테이블을 통해 파악할 계획입니다.
