### ISSUE TITLE
프론트 단에서 테스트를 위한 별도의 서버가 필요합니다.

### ISSUE THREAD

**Issue by gigantes88** [YoungHeaKim/beagleWPSN#35]
프론트 단에서 로그인 관련 테스트를 위한 별도의 서버가 필요합니다.

다른 조 한 것 참조해보니 AWS에 백 서버를 올려서 프론트에서도 테스트 하게 한다고 합니다.

**Comment by YoungHeaKim** [comment]
https://test.younghea.com -> 서버를 올렸습니다
